"""Shared constants for the datapackage skill tests.

These values describe the canonical properties of the example weather dataset
generated by scripts/generate_examples.py.  If the script parameters change
(e.g. more stations or a different date range), update these constants too.
"""

from pathlib import Path

# Root of the generated example packages
EXAMPLES = Path(__file__).parent.parent / "assets" / "examples"

# ── Dataset dimensions ────────────────────────────────────────────────────────
STATION_COUNT = 5
READING_COUNT = 150  # 5 stations × 30 daily readings

# ── Descriptor structure ──────────────────────────────────────────────────────
RESOURCE_NAMES = ["stations", "daily-readings"]

STATION_COLUMNS = [
    "station_id",
    "station_name",
    "latitude",
    "longitude",
    "elevation_m",
    "active",
    "commissioned_date",
]

READING_COLUMNS = [
    "station_id",
    "date",
    "temp_min_c",
    "temp_max_c",
    "precipitation_mm",
    "wind_speed_avg_ms",
]

# Date columns that should have a proper date type (not string) in typed backends
DATE_COLUMNS = {
    "stations": ["commissioned_date"],
    "daily-readings": ["date"],
}
